import { BookOpen, Sparkles } from 'lucide-react'
import { CourseCard } from '../../components/courses/course-card'
import { PageContainer } from '../../components/layout/app-shell'
import { PageTransition } from '../../components/shared/page-transition'
import { ProgressBar } from '../../components/shared/progress-bar'
import { Badge } from '../../components/ui/badge'
import { Card } from '../../components/ui/card'
import { courses } from '../../data/mock-data'

export function CoursesPage() { const overall = Math.round(courses.reduce((sum, course) => sum + course.progress, 0) / courses.length); return <PageTransition><PageContainer className="space-y-8"><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Badge>Learning space</Badge><h2 className="mt-3 text-3xl font-semibold tracking-[-0.055em] text-foreground sm:text-4xl">Make progress visible.</h2><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground sm:text-base">A calm view of your courses, materials, and the work that deserves attention next.</p></div><Card className="min-w-[14rem] p-4"><div className="flex items-center justify-between text-xs"><span className="font-medium text-muted-foreground">Semester progress</span><span className="font-semibold text-foreground">{overall}%</span></div><ProgressBar className="mt-3" value={overall} /></Card></section><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{courses.map((course) => <CourseCard course={course} expanded key={course.id} />)}</section><section className="grid gap-4 lg:grid-cols-3" id="learning"><Card className="lg:col-span-2"><div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-brand/10 text-brand"><Sparkles className="size-5" /></span><div><p className="text-sm font-semibold text-foreground">Your learning pattern is working.</p><p className="mt-1 text-sm leading-6 text-muted-foreground">You retain more when you alternate technical deep work with product-design synthesis. Keep the 45–25 minute cadence this week.</p></div></div></Card><Card><div className="flex items-center gap-2 text-sm font-semibold text-foreground"><BookOpen className="size-4 text-brand" />Next study move</div><p className="mt-2 text-sm text-muted-foreground">Review the neural networks walkthrough before your next ML session.</p></Card></section></PageContainer></PageTransition> }
