import { ArrowUpRight, CalendarDays, Sparkles } from 'lucide-react'
import { motion } from 'framer-motion'
import type { Opportunity } from '../../data/mock-data'
import { Badge } from '../ui/badge'
import { Button } from '../ui/button'

export function OpportunityCard({ opportunity }: { opportunity: Opportunity }) {
  return <motion.article className="relative overflow-hidden rounded-2xl border border-border bg-surface p-5 shadow-card" whileHover={{ y: -3 }}><div className={`absolute right-0 top-0 h-24 w-24 -translate-y-1/2 translate-x-1/2 rounded-full bg-gradient-to-br ${opportunity.accent} opacity-10 blur-2xl`} /><div className="relative"><div className="flex items-start justify-between gap-3"><Badge variant="outline">{opportunity.kind}</Badge><span className="grid size-11 place-items-center rounded-2xl bg-brand/10 text-sm font-bold text-brand">{opportunity.match}%</span></div><h3 className="mt-4 text-base font-semibold tracking-[-0.03em] text-foreground">{opportunity.title}</h3><p className="mt-1 text-sm text-muted-foreground">{opportunity.organization}</p><div className="mt-4 flex items-center gap-1.5 text-xs font-medium text-warning"><CalendarDays className="size-3.5" />{opportunity.deadline}</div><div className="mt-4 flex flex-wrap gap-1.5">{opportunity.skills.map((skill) => <span className="rounded-md bg-muted px-2 py-1 text-[11px] font-medium text-muted-foreground" key={skill}>{skill}</span>)}</div><div className="mt-4 rounded-xl bg-brand/[0.055] p-3"><div className="flex items-center gap-1.5 text-xs font-semibold text-brand"><Sparkles className="size-3.5" />Why it matches you</div><p className="mt-1.5 text-xs leading-5 text-muted-foreground">{opportunity.reason}</p></div><div className="mt-4 flex items-center justify-between gap-3"><span className="text-xs text-muted-foreground">{opportunity.eligibility}</span><Button aria-label={`View ${opportunity.title}`} size="sm" variant="ghost"><ArrowUpRight className="size-4" /></Button></div></div></motion.article>
}
