import { AnimatePresence, motion } from 'framer-motion'
import { ArrowRight, BookOpen, Bot, CalendarDays, CheckCircle2, ClipboardCheck, ExternalLink, GraduationCap, Menu, MessageCircle, Search, ShieldCheck, Sparkles, X, type LucideIcon } from 'lucide-react'
import { useEffect, useState, type ReactNode } from 'react'
import { Link } from 'react-router-dom'
import { AppLogo } from '../components/shared/app-logo'
import { ThemeToggle } from '../components/shared/theme-toggle'
import { Badge } from '../components/ui/badge'
import { Button } from '../components/ui/button'

const glass = 'liquid-glass border border-white/80 shadow-[0_24px_70px_-35px_rgba(43,55,90,.35)]'
const reveal = { initial: { opacity: 0, y: 22, scale: .98, filter: 'blur(8px)' }, whileInView: { opacity: 1, y: 0, scale: 1, filter: 'blur(0px)' }, viewport: { once: true, amount: .2 }, transition: { type: 'spring' as const, stiffness: 130, damping: 18, mass: .7 } }

export function LandingPage() {
  const [palette, setPalette] = useState(false)
  const [menu, setMenu] = useState(false)
  const [scrolled, setScrolled] = useState(false)

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 32)
    const onKey = (event: KeyboardEvent) => {
      if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') {
        event.preventDefault()
        setPalette(true)
      }
    }
    onScroll()
    window.addEventListener('scroll', onScroll, { passive: true })
    window.addEventListener('keydown', onKey)
    return () => { window.removeEventListener('scroll', onScroll); window.removeEventListener('keydown', onKey) }
  }, [])

  return <main className="landing-surface noise-overlay relative min-h-screen overflow-hidden bg-[#f7f8fa] text-slate-900">
    <ParticleField />
    <motion.header animate={{ opacity: 1, y: 0 }} className="fixed inset-x-0 top-0 z-40 px-3 pt-3 sm:px-6 sm:pt-5" initial={{ opacity: 0, y: -14 }} transition={{ type: 'spring', stiffness: 160, damping: 20 }}>
      <div className={`${glass} mx-auto flex ${scrolled ? 'h-12 rounded-xl' : 'h-14 rounded-2xl'} max-w-6xl items-center justify-between px-3 transition-[height,border-radius,box-shadow] duration-300 sm:px-5`}>
        <AppLogo />
        <nav className="hidden items-center gap-1 text-sm text-slate-500 md:flex">
          {['Academics', 'Opportunities', 'Complaints', 'Campus AI'].map((item) => <a className="underline-reveal rounded-full px-3 py-2 transition-colors hover:text-slate-950" href={`#${item.toLowerCase().replace(' ', '-')}`} key={item}>{item}</a>)}
        </nav>
        <div className="flex items-center gap-1.5">
          <button aria-label="Open search" className="grid size-9 place-items-center rounded-xl text-slate-500 transition hover:bg-white/70 hover:text-slate-950 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-300" onClick={() => setPalette(true)} type="button"><Search className="size-4" /></button>
          <ThemeToggle />
          <Link className="hidden rounded-xl border border-slate-200/80 bg-white/70 px-3.5 py-2 text-xs font-semibold text-slate-800 transition hover:-translate-y-0.5 hover:border-orange-200 hover:shadow-sm sm:inline-flex" to="/login">Login</Link>
          <Link className="hidden rounded-xl bg-slate-950 px-3.5 py-2 text-xs font-semibold text-white transition hover:-translate-y-0.5 hover:shadow-lg sm:inline-flex" to="/student">Enter CampusOS</Link>
          <button aria-label="Open menu" className="grid size-9 place-items-center rounded-xl text-slate-500 transition hover:bg-white/70 md:hidden" onClick={() => setMenu(true)} type="button"><Menu className="size-5" /></button>
        </div>
      </div>
    </motion.header>

    <section className="relative isolate flex min-h-[840px] items-center justify-center px-4 pb-24 pt-36 sm:px-6">
      <div className="hero-atmosphere pointer-events-none absolute inset-0 -z-10" />
      <div className="mx-auto w-full max-w-6xl text-center">
        <motion.div animate={{ opacity: 1, y: 0, filter: 'blur(0px)' }} initial={{ opacity: 0, y: 14, filter: 'blur(8px)' }} transition={{ delay: .1, duration: .7 }}>
          <Badge className="border-orange-200/80 bg-white/70 text-orange-700"><Sparkles className="size-3" />AI-native campus ecosystem</Badge>
          <h1 className="mx-auto mt-7 max-w-5xl text-[clamp(3.35rem,9vw,8rem)] font-medium leading-[.88] tracking-[-.095em]">Your Campus.<br /><span className="bg-gradient-to-r from-slate-950 via-slate-700 to-slate-400 bg-clip-text text-transparent">Intelligently Connected.</span></h1>
          <p className="mx-auto mt-8 max-w-2xl text-base leading-7 text-slate-600 sm:text-lg">An AI-powered digital campus ecosystem for learning, communication, opportunities and campus operations.</p>
          <div className="mt-9 flex flex-wrap justify-center gap-3"><Link to="/student"><Button size="lg" className="group"><span>Enter CampusOS</span><ArrowRight className="size-4 transition-transform duration-200 group-hover:translate-x-1" /></Button></Link><a className="inline-flex h-12 items-center gap-2 rounded-xl border border-slate-200/90 bg-white/60 px-5 text-sm font-semibold text-slate-800 transition hover:-translate-y-0.5 hover:border-orange-200 hover:bg-white hover:shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-300" href="#campus-ai">Explore Campus AI <Bot className="size-4 text-orange-600 transition-transform group-hover:translate-x-1" /></a></div>
        </motion.div>

        <motion.div animate={{ opacity: 1, y: 0, rotateX: 5, rotateY: -2 }} className="relative mx-auto mt-20 max-w-5xl [perspective:1400px]" initial={{ opacity: 0, y: 38, rotateX: 12, rotateY: 2 }} transition={{ delay: .32, type: 'spring', stiffness: 75, damping: 17 }}>
          <div className="absolute -inset-12 rounded-[5rem] bg-[radial-gradient(circle_at_50%_40%,rgba(165,243,252,.24),transparent_45%),radial-gradient(circle_at_75%_65%,rgba(196,181,253,.18),transparent_35%)] blur-3xl" />
          <div className={`${glass} hero-object relative mx-auto rounded-[2rem] p-3 text-left sm:p-5`}>
            <div className="flex items-center justify-between border-b border-slate-200/70 px-2 pb-3"><div className="flex items-center gap-2"><span className="grid size-7 place-items-center rounded-lg bg-slate-950 text-white"><GraduationCap className="size-4" /></span><span className="text-xs font-semibold text-slate-700">CampusOS / Intelligence layer</span></div><span className="flex items-center gap-1.5 text-[11px] text-emerald-600"><span className="size-1.5 animate-pulse rounded-full bg-emerald-400" />Systems clear</span></div>
            <div className="grid gap-3 p-2 pt-4 sm:grid-cols-[1.2fr_.8fr_.8fr]">
              <div className="rounded-2xl border border-orange-100 bg-white/72 p-4 shadow-[0_16px_35px_-28px_rgba(234,88,12,.35)]"><div className="flex items-center gap-2 text-orange-600"><Bot className="size-4" /><span className="text-[10px] font-semibold uppercase tracking-[.16em]">Campus AI</span></div><p className="mt-6 max-w-[16rem] text-lg font-medium tracking-[-.03em] text-slate-800">Your best focus window is now.</p><p className="mt-2 text-xs leading-5 text-slate-500">Finish classifier analysis before 10:30 AM.</p><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-orange-100"><div className="h-full w-[72%] rounded-full bg-gradient-to-r from-orange-400 to-amber-300" /></div></div>
              <MetricCard label="Attendance" value="87%" detail="+2.1% this month" icon={CheckCircle2} tone="green" />
              <MetricCard label="Opportunity match" value="92%" detail="3 roles fit your profile" icon={Sparkles} tone="violet" />
            </div>
            <div className="grid gap-3 px-2 pb-2 sm:grid-cols-2"><FloatCard icon={ShieldCheck} label="Complaint intelligence" title="Wi‑Fi issue routed" detail="Network Operations · SLA 24h" /><FloatCard icon={CalendarDays} label="Latest from GIST" title="April/May 2026 results" detail="Official examination update available" /></div>
          </div>
        </motion.div>
        <div className="mt-10 flex justify-center"><span className="scroll-cue text-[10px] uppercase tracking-[.24em] text-slate-400">Scroll to explore</span></div>
      </div>
    </section>

    <StorySection id="academics" eyebrow="01 · Academics" title="Learning that understands the next step." copy="Course progress, attendance, and AI recommendations in one calm, connected view." visual={<div className="grid gap-3 sm:grid-cols-[1.1fr_.9fr]"><GlassStat icon={BookOpen} title="Machine Learning" detail="Module 06 · Classification" progress={72} /><div id="opportunities" className="rounded-2xl border border-violet-100 bg-white/65 p-5 shadow-[0_20px_50px_-38px_rgba(124,58,237,.38)]"><div className="flex items-center gap-2 text-violet-600"><Sparkles className="size-4" /><span className="text-[10px] font-semibold uppercase tracking-[.16em]">Opportunity match</span></div><p className="mt-5 text-3xl font-medium tracking-[-.06em] text-slate-900">92%</p><p className="mt-1 text-xs leading-5 text-slate-500">AI matched you to 3 active roles.</p><Link className="mt-5 inline-flex items-center gap-1 text-xs font-semibold text-violet-700" to="/student/opportunities">Explore roles <ArrowRight className="size-3.5" /></Link></div></div>} />
    <StorySection id="complaints" eyebrow="02 · Complaint intelligence" title="Every issue finds its owner." copy="AI classifies the signal, routes it to the right team, and keeps resolution visible from submission to close." visual={<div className={`${glass} rounded-2xl p-5`}><div className="flex items-center justify-between"><span className="text-sm font-semibold text-slate-800">Projector not working in CSE Lab</span><Badge variant="warning">In review</Badge></div><div className="mt-7 grid grid-cols-4 gap-2">{['Submitted', 'AI classified', 'Routed', 'Resolved'].map((step, index) => <div className="relative" key={step}><div className={`mx-auto grid size-8 place-items-center rounded-full ${index < 3 ? 'bg-orange-500 text-white' : 'border border-slate-200 bg-white text-slate-400'}`}>{index < 3 ? <CheckCircle2 className="size-4" /> : <span className="size-2 rounded-full bg-slate-300" />}</div>{index < 3 ? <span className="absolute left-[calc(50%+1rem)] right-[calc(-50%+1rem)] top-4 h-px bg-orange-200" /> : null}<p className="mt-2 text-center text-[10px] text-slate-500">{step}</p></div>)}</div><Link className="mt-6 inline-flex items-center gap-1.5 text-xs font-semibold text-orange-700" to="/student/complaints">Open complaint intelligence <ArrowRight className="size-3.5" /></Link></div>} />
    <StorySection id="gist" eyebrow="03 · GIST updates" title="Official updates, made legible." copy="CampusOS keeps the latest examination results, circulars, and academic notices close to the people they affect." visual={<div className="grid gap-3 sm:grid-cols-2"><UpdateCard title="B.Tech Regular & Supplementary Examinations" detail="April/May 2026 · Official examination portal" /><UpdateCard title="Academic notifications" detail="Notice board · Source verified" /></div>} />
    <StorySection id="campus-ai" eyebrow="04 · Campus AI" title="Ask the campus. Get a useful next move." copy="A contextual copilot for questions about attendance, exams, courses, complaints, and campus life." visual={<div className={`${glass} rounded-2xl p-4`}><div className="flex items-center gap-2 border-b border-slate-200/70 pb-3"><span className="ai-indicator grid size-8 place-items-center rounded-xl bg-orange-50 text-orange-600"><Bot className="size-4" /></span><span className="text-sm font-medium text-slate-800">Campus AI</span><span className="ml-auto text-[11px] text-emerald-600">Online</span></div><div className="space-y-3 py-5 text-sm"><div className="ml-auto max-w-[85%] rounded-2xl rounded-tr-md bg-slate-100 p-3 text-slate-700">What should I focus on today?</div><div className="max-w-[90%] rounded-2xl rounded-tl-md bg-orange-50 p-3 leading-6 text-orange-900">Start with classifier analysis. You are one focused session from closing the week.</div></div><Link className="inline-flex items-center gap-1.5 text-xs font-semibold text-orange-700" to="/student/ai">Open Campus AI <ArrowRight className="size-3.5" /></Link></div>} />
    <section className="mx-auto max-w-6xl px-4 pb-28 pt-20 text-center sm:px-6"><motion.div {...reveal} className="mx-auto max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-orange-600">05 · The connected campus</p><h2 className="mt-4 text-4xl font-medium tracking-[-.07em] sm:text-6xl">A quieter, clearer way to move through campus.</h2><p className="mx-auto mt-5 max-w-xl text-base leading-7 text-slate-600">Enter CampusOS and see what a modern institution can feel like when every signal has a next step.</p><Link className="mt-8 inline-flex" to="/student"><Button size="lg">Enter CampusOS <ArrowRight className="size-4" /></Button></Link></motion.div></section>

    <AnimatePresence>{palette ? <CommandPalette close={() => setPalette(false)} /> : null}</AnimatePresence>
    <AnimatePresence>{menu ? <motion.div animate={{ opacity: 1 }} className="fixed inset-0 z-50 bg-white/92 p-4 backdrop-blur-2xl md:hidden" exit={{ opacity: 0 }} initial={{ opacity: 0 }}><div className="flex justify-end"><button aria-label="Close menu" className="grid size-10 place-items-center rounded-xl text-slate-500 hover:bg-slate-100" onClick={() => setMenu(false)} type="button"><X /></button></div><nav className="mt-12 grid gap-3 px-4 text-2xl font-medium tracking-[-.04em]">{['Academics', 'Opportunities', 'Complaints', 'Campus AI'].map((item) => <a className="rounded-2xl px-4 py-3 transition hover:bg-orange-50 hover:text-orange-700" href={`#${item.toLowerCase().replace(' ', '-')}`} key={item} onClick={() => setMenu(false)}>{item}</a>)}<Link className="rounded-2xl bg-slate-950 px-4 py-3 text-center text-base font-semibold text-white" to="/student">Enter CampusOS</Link></nav></motion.div> : null}</AnimatePresence>
  </main>
}

function StorySection({ id, eyebrow, title, copy, visual }: { id: string; eyebrow: string; title: string; copy: string; visual: ReactNode }) { return <section className="mx-auto max-w-6xl scroll-mt-24 px-4 py-20 sm:px-6" id={id}><div className="grid items-center gap-10 lg:grid-cols-[.82fr_1.18fr] lg:gap-20"><motion.div {...reveal}><p className="text-xs font-semibold uppercase tracking-[.2em] text-orange-600">{eyebrow}</p><h2 className="mt-4 max-w-xl text-4xl font-medium leading-[.98] tracking-[-.065em] sm:text-6xl">{title}</h2><p className="mt-5 max-w-lg text-base leading-7 text-slate-600">{copy}</p></motion.div><motion.div {...reveal} className="story-visual">{visual}</motion.div></div></section> }
function MetricCard({ icon: Icon, label, value, detail, tone }: { icon: LucideIcon; label: string; value: string; detail: string; tone: 'green' | 'violet' }) { return <div className={`rounded-2xl border p-4 ${tone === 'green' ? 'border-emerald-100 bg-emerald-50/60' : 'border-violet-100 bg-violet-50/60'}`}><Icon className={`size-4 ${tone === 'green' ? 'text-emerald-600' : 'text-violet-600'}`} /><p className="mt-5 text-3xl font-medium tracking-[-.06em] text-slate-900">{value}</p><p className="mt-1 text-xs font-semibold text-slate-700">{label}</p><p className="mt-1 text-[11px] leading-5 text-slate-500">{detail}</p></div> }
function FloatCard({ icon: Icon, label, title, detail }: { icon: LucideIcon; label: string; title: string; detail: string }) { return <motion.div className="hero-float rounded-2xl border border-slate-200 bg-white/70 p-4 transition hover:-translate-y-1 hover:border-orange-200 hover:shadow-[0_18px_40px_-28px_rgba(234,88,12,.35)]" whileHover={{ scale: 1.01, rotateX: 1.5, rotateY: -1.5 }} transition={{ type: 'spring', stiffness: 280, damping: 22 }}><Icon className="size-4 text-orange-600" /><p className="mt-5 text-[10px] font-semibold uppercase tracking-[.16em] text-slate-400">{label}</p><p className="mt-1.5 text-sm font-semibold text-slate-800">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{detail}</p></motion.div> }
function GlassStat({ icon: Icon, title, detail, progress }: { icon: LucideIcon; title: string; detail: string; progress: number }) { return <div className={`${glass} rounded-2xl p-5`}><div className="flex items-center gap-2 text-orange-600"><Icon className="size-4" /><span className="text-[10px] font-semibold uppercase tracking-[.16em]">Course progress</span></div><p className="mt-7 text-xl font-medium tracking-[-.04em] text-slate-900">{title}</p><p className="mt-1 text-xs text-slate-500">{detail}</p><div className="mt-6 flex items-center justify-between text-xs font-semibold text-slate-600"><span>Progress</span><span>{progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-orange-100"><motion.div animate={{ width: `${progress}%` }} className="h-full rounded-full bg-gradient-to-r from-orange-400 to-amber-300" initial={{ width: 0 }} transition={{ delay: .25, duration: .8 }} /></div></div> }
function UpdateCard({ title, detail }: { title: string; detail: string }) { return <div className="group rounded-2xl border border-slate-200/80 bg-white/70 p-5 transition hover:-translate-y-1 hover:border-orange-200 hover:shadow-[0_20px_50px_-34px_rgba(234,88,12,.35)]"><div className="flex items-center justify-between"><span className="grid size-9 place-items-center rounded-xl bg-orange-50 text-orange-600"><ExternalLink className="size-4" /></span><Badge className="border-emerald-100 bg-emerald-50 text-emerald-700">Source verified</Badge></div><p className="mt-6 text-sm font-semibold leading-5 text-slate-800">{title}</p><p className="mt-2 text-xs leading-5 text-slate-500">{detail}</p><a className="mt-5 inline-flex items-center gap-1.5 text-xs font-semibold text-orange-700" href="https://gist.edu.in/" rel="noreferrer" target="_blank">View GIST source <ExternalLink className="size-3.5" /></a></div> }
function ParticleField() { return <div aria-hidden="true" className="particle-field" /> }
function CommandPalette({ close }: { close: () => void }) { const items = [{ label: 'Ask Campus AI', to: '/student/ai', icon: Bot }, { label: 'View Examination Results', to: '/student', icon: CalendarDays }, { label: 'Submit Complaint', to: '/student/complaints', icon: ClipboardCheck }, { label: 'Find Opportunities', to: '/student/opportunities', icon: Sparkles }, { label: 'Open Career Planner', to: '/student/career', icon: MessageCircle }]; return <motion.div animate={{ opacity: 1 }} className="fixed inset-0 z-[80] flex items-start justify-center bg-slate-900/20 px-4 pt-[13vh] backdrop-blur-md" exit={{ opacity: 0 }} initial={{ opacity: 0 }} onMouseDown={close}><motion.div animate={{ opacity: 1, scale: 1, y: 0 }} className="liquid-glass w-full max-w-xl overflow-hidden rounded-2xl border border-white/70" exit={{ opacity: 0, scale: .97, y: 10 }} initial={{ opacity: 0, scale: .97, y: 10 }} onMouseDown={(event) => event.stopPropagation()}><div className="flex items-center gap-3 border-b border-slate-200/80 px-4 py-4"><Search className="size-5 text-slate-400" /><input autoFocus className="min-w-0 flex-1 bg-transparent text-base text-slate-900 outline-none placeholder:text-slate-400" placeholder="Search your campus..." /><kbd className="rounded-md bg-slate-100 px-2 py-1 text-[10px] text-slate-500">⌘ K</kbd></div><div className="p-3"><p className="px-2 pb-2 text-[10px] font-semibold uppercase tracking-[.16em] text-slate-400">Recent · Academic · Campus · AI Actions</p>{items.map(({ label, to, icon: Icon }) => <Link className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm text-slate-700 transition hover:bg-orange-50 hover:text-orange-700" key={label} onClick={close} to={to}><Icon className="size-4 text-orange-600" />{label}<ArrowRight className="ml-auto size-3.5 text-slate-300" /></Link>)}</div></motion.div></motion.div> }