import { ArrowRight, Building2, GraduationCap, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import { AppLogo } from '../components/shared/app-logo'
import { Badge } from '../components/ui/badge'
import { buttonStyles } from '../components/ui/button'

export function LoginPage() {
  return <main className="page-glow noise-overlay grid min-h-screen place-items-center overflow-hidden px-4 py-8 sm:py-12"><section className="relative w-full max-w-5xl overflow-hidden rounded-[2rem] border border-border bg-surface/90 shadow-float backdrop-blur-xl"><div className="absolute -right-24 -top-28 size-72 rounded-full bg-brand/10 blur-3xl" /><div className="relative grid lg:grid-cols-[1.05fr_.95fr]"><div className="p-6 sm:p-10 lg:p-12"><AppLogo /><div className="mt-14 max-w-md"><Badge variant="ai"><Sparkles className="size-3.5" />Campus intelligence, composed</Badge><h1 className="mt-5 text-4xl font-semibold tracking-[-.07em] text-foreground sm:text-5xl">Enter your campus workspace.</h1><p className="mt-4 text-sm leading-6 text-muted-foreground sm:text-base">Authentication is intentionally out of scope for this frontend MVP. Choose a workspace to explore the CampusOS experience.</p></div><div className="mt-8 space-y-3"><Link className={buttonStyles({ size: 'lg', className: 'w-full justify-between' })} to="/student"><span className="flex items-center gap-2"><GraduationCap className="size-4" />Open student dashboard</span><ArrowRight className="size-4" /></Link><Link className={buttonStyles({ size: 'lg', variant: 'secondary', className: 'w-full justify-between' })} to="/admin"><span className="flex items-center gap-2"><Building2 className="size-4" />Open admin command center</span><ArrowRight className="size-4" /></Link></div><Link className="mt-6 inline-flex text-sm font-semibold text-brand transition-colors hover:text-brand-secondary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" to="/">Back to CampusOS home</Link></div><aside className="hidden border-l border-border bg-muted/45 p-10 lg:flex lg:flex-col lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand">GIST · CampusOS</p><h2 className="mt-5 text-3xl font-semibold tracking-[-.06em] text-foreground">One connected layer for the modern campus.</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">Learning, opportunities, complaints, announcements, and campus AI in a calm operating picture.</p></div><div className="space-y-3"><TrustItem label="AI-first student experience" /><TrustItem label="Official GIST information context" /><TrustItem label="Operations with visible accountability" /></div></aside></div></section></main>
}

function TrustItem({ label }: { label: string }) { return <div className="flex items-center gap-3 rounded-xl border border-border bg-surface/75 p-3 text-sm font-medium text-foreground"><span className="grid size-7 place-items-center rounded-lg bg-success/10 text-success">✓</span>{label}</div> }
