import { ArrowUpRight, CheckCircle2, ClipboardCheck, UsersRound } from 'lucide-react'
import { motion } from 'framer-motion'
import { Link } from 'react-router-dom'
import type { Course } from '../../data/mock-data'
import { ProgressBar } from '../shared/progress-bar'
import { Badge } from '../ui/badge'

export function CourseCard({ course, expanded = false }: { course: Course; expanded?: boolean }) {
  return <motion.article whileHover={{ y: -3 }}><Link className="group block overflow-hidden rounded-2xl border border-border bg-surface shadow-card transition-[border-color,box-shadow] hover:border-border-strong hover:shadow-card-hover" to={`/student/courses/${course.id}`}><div className={`h-1.5 bg-gradient-to-r ${course.color}`} /><div className="p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><div><Badge variant="outline">{course.code}</Badge><h3 className="mt-3 text-base font-semibold tracking-[-0.03em] text-foreground">{course.title}</h3><p className="mt-1 text-sm text-muted-foreground">{course.faculty}</p></div><ArrowUpRight className="mt-1 size-4 text-muted-foreground transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></div><div className="mt-5"><div className="mb-2 flex items-center justify-between text-xs"><span className="font-medium text-muted-foreground">Course progress</span><span className="font-semibold text-foreground">{course.progress}%</span></div><ProgressBar value={course.progress} /></div><div className="mt-4 grid grid-cols-2 gap-3 border-t border-border pt-4 text-xs"><span className="flex items-center gap-1.5 text-muted-foreground"><UsersRound className="size-3.5 text-success" /><b className="font-semibold text-foreground">{course.attendance}%</b> attendance</span><span className="flex items-center gap-1.5 text-muted-foreground"><ClipboardCheck className="size-3.5 text-brand" /><b className="font-semibold text-foreground">{course.assignments.done}/{course.assignments.total}</b> done</span></div>{expanded ? <div className="mt-4 flex items-center gap-1.5 text-xs text-muted-foreground"><CheckCircle2 className="size-3.5 text-success" />Next class · {course.nextClass}</div> : null}</div></Link></motion.article>
}
